{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Sensual content project \n",
    "# Importing necessary library\n",
    "from PIL import Image\n",
    "import requests\n",
    "import os\n",
    "import cv2\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pytesseract"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the CSV file with image URLs using pandas\n",
    "df = pd.read_csv('image2.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the reference \"18+ banner\" image\n",
    "reference_banner_path = r'banner.jpg'  # Change to your reference image's path\n",
    "reference_banner = cv2.imread(reference_banner_path)\n",
    "reference_hsv = cv2.cvtColor(reference_banner, cv2.COLOR_BGR2HSV)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "TesseractNotFoundError",
     "evalue": "tesseract is not installed or it's not in your PATH. See README file for more information.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytesseract\\pytesseract.py:255\u001b[0m, in \u001b[0;36mrun_tesseract\u001b[1;34m(input_filename, output_filename_base, extension, lang, config, nice, timeout)\u001b[0m\n\u001b[0;32m    254\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 255\u001b[0m     proc \u001b[39m=\u001b[39m subprocess\u001b[39m.\u001b[39;49mPopen(cmd_args, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49msubprocess_args())\n\u001b[0;32m    256\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mOSError\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[1;32mc:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\subprocess.py:1024\u001b[0m, in \u001b[0;36mPopen.__init__\u001b[1;34m(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize, process_group)\u001b[0m\n\u001b[0;32m   1021\u001b[0m             \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstderr \u001b[39m=\u001b[39m io\u001b[39m.\u001b[39mTextIOWrapper(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstderr,\n\u001b[0;32m   1022\u001b[0m                     encoding\u001b[39m=\u001b[39mencoding, errors\u001b[39m=\u001b[39merrors)\n\u001b[1;32m-> 1024\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_child(args, executable, preexec_fn, close_fds,\n\u001b[0;32m   1025\u001b[0m                         pass_fds, cwd, env,\n\u001b[0;32m   1026\u001b[0m                         startupinfo, creationflags, shell,\n\u001b[0;32m   1027\u001b[0m                         p2cread, p2cwrite,\n\u001b[0;32m   1028\u001b[0m                         c2pread, c2pwrite,\n\u001b[0;32m   1029\u001b[0m                         errread, errwrite,\n\u001b[0;32m   1030\u001b[0m                         restore_signals,\n\u001b[0;32m   1031\u001b[0m                         gid, gids, uid, umask,\n\u001b[0;32m   1032\u001b[0m                         start_new_session, process_group)\n\u001b[0;32m   1033\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m   1034\u001b[0m     \u001b[39m# Cleanup if the child failed starting.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\subprocess.py:1493\u001b[0m, in \u001b[0;36mPopen._execute_child\u001b[1;34m(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session, unused_process_group)\u001b[0m\n\u001b[0;32m   1492\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m-> 1493\u001b[0m     hp, ht, pid, tid \u001b[39m=\u001b[39m _winapi\u001b[39m.\u001b[39;49mCreateProcess(executable, args,\n\u001b[0;32m   1494\u001b[0m                              \u001b[39m# no special security\u001b[39;49;00m\n\u001b[0;32m   1495\u001b[0m                              \u001b[39mNone\u001b[39;49;00m, \u001b[39mNone\u001b[39;49;00m,\n\u001b[0;32m   1496\u001b[0m                              \u001b[39mint\u001b[39;49m(\u001b[39mnot\u001b[39;49;00m close_fds),\n\u001b[0;32m   1497\u001b[0m                              creationflags,\n\u001b[0;32m   1498\u001b[0m                              env,\n\u001b[0;32m   1499\u001b[0m                              cwd,\n\u001b[0;32m   1500\u001b[0m                              startupinfo)\n\u001b[0;32m   1501\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m   1502\u001b[0m     \u001b[39m# Child is launched. Close the parent's copy of those pipe\u001b[39;00m\n\u001b[0;32m   1503\u001b[0m     \u001b[39m# handles that only the child should have open.  You need\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1506\u001b[0m     \u001b[39m# pipe will not close when the child process exits and the\u001b[39;00m\n\u001b[0;32m   1507\u001b[0m     \u001b[39m# ReadFile will hang.\u001b[39;00m\n",
      "\u001b[1;31mFileNotFoundError\u001b[0m: [WinError 2] The system cannot find the file specified",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mTesseractNotFoundError\u001b[0m                    Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[6], line 13\u001b[0m\n\u001b[0;32m     10\u001b[0m image \u001b[39m=\u001b[39m Image\u001b[39m.\u001b[39mopen(image_path)\n\u001b[0;32m     12\u001b[0m \u001b[39m# Extract text from the image\u001b[39;00m\n\u001b[1;32m---> 13\u001b[0m text \u001b[39m=\u001b[39m pytesseract\u001b[39m.\u001b[39;49mimage_to_string(image)\n\u001b[0;32m     15\u001b[0m \u001b[39m# Print the extracted text\u001b[39;00m\n\u001b[0;32m     16\u001b[0m \u001b[39mprint\u001b[39m(text)\n",
      "File \u001b[1;32mc:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytesseract\\pytesseract.py:423\u001b[0m, in \u001b[0;36mimage_to_string\u001b[1;34m(image, lang, config, nice, output_type, timeout)\u001b[0m\n\u001b[0;32m    418\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    419\u001b[0m \u001b[39mReturns the result of a Tesseract OCR run on the provided image to string\u001b[39;00m\n\u001b[0;32m    420\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    421\u001b[0m args \u001b[39m=\u001b[39m [image, \u001b[39m'\u001b[39m\u001b[39mtxt\u001b[39m\u001b[39m'\u001b[39m, lang, config, nice, timeout]\n\u001b[1;32m--> 423\u001b[0m \u001b[39mreturn\u001b[39;00m {\n\u001b[0;32m    424\u001b[0m     Output\u001b[39m.\u001b[39;49mBYTES: \u001b[39mlambda\u001b[39;49;00m: run_and_get_output(\u001b[39m*\u001b[39;49m(args \u001b[39m+\u001b[39;49m [\u001b[39mTrue\u001b[39;49;00m])),\n\u001b[0;32m    425\u001b[0m     Output\u001b[39m.\u001b[39;49mDICT: \u001b[39mlambda\u001b[39;49;00m: {\u001b[39m'\u001b[39;49m\u001b[39mtext\u001b[39;49m\u001b[39m'\u001b[39;49m: run_and_get_output(\u001b[39m*\u001b[39;49margs)},\n\u001b[0;32m    426\u001b[0m     Output\u001b[39m.\u001b[39;49mSTRING: \u001b[39mlambda\u001b[39;49;00m: run_and_get_output(\u001b[39m*\u001b[39;49margs),\n\u001b[0;32m    427\u001b[0m }[output_type]()\n",
      "File \u001b[1;32mc:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytesseract\\pytesseract.py:426\u001b[0m, in \u001b[0;36mimage_to_string.<locals>.<lambda>\u001b[1;34m()\u001b[0m\n\u001b[0;32m    418\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    419\u001b[0m \u001b[39mReturns the result of a Tesseract OCR run on the provided image to string\u001b[39;00m\n\u001b[0;32m    420\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    421\u001b[0m args \u001b[39m=\u001b[39m [image, \u001b[39m'\u001b[39m\u001b[39mtxt\u001b[39m\u001b[39m'\u001b[39m, lang, config, nice, timeout]\n\u001b[0;32m    423\u001b[0m \u001b[39mreturn\u001b[39;00m {\n\u001b[0;32m    424\u001b[0m     Output\u001b[39m.\u001b[39mBYTES: \u001b[39mlambda\u001b[39;00m: run_and_get_output(\u001b[39m*\u001b[39m(args \u001b[39m+\u001b[39m [\u001b[39mTrue\u001b[39;00m])),\n\u001b[0;32m    425\u001b[0m     Output\u001b[39m.\u001b[39mDICT: \u001b[39mlambda\u001b[39;00m: {\u001b[39m'\u001b[39m\u001b[39mtext\u001b[39m\u001b[39m'\u001b[39m: run_and_get_output(\u001b[39m*\u001b[39margs)},\n\u001b[1;32m--> 426\u001b[0m     Output\u001b[39m.\u001b[39mSTRING: \u001b[39mlambda\u001b[39;00m: run_and_get_output(\u001b[39m*\u001b[39;49margs),\n\u001b[0;32m    427\u001b[0m }[output_type]()\n",
      "File \u001b[1;32mc:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytesseract\\pytesseract.py:288\u001b[0m, in \u001b[0;36mrun_and_get_output\u001b[1;34m(image, extension, lang, config, nice, timeout, return_bytes)\u001b[0m\n\u001b[0;32m    277\u001b[0m \u001b[39mwith\u001b[39;00m save(image) \u001b[39mas\u001b[39;00m (temp_name, input_filename):\n\u001b[0;32m    278\u001b[0m     kwargs \u001b[39m=\u001b[39m {\n\u001b[0;32m    279\u001b[0m         \u001b[39m'\u001b[39m\u001b[39minput_filename\u001b[39m\u001b[39m'\u001b[39m: input_filename,\n\u001b[0;32m    280\u001b[0m         \u001b[39m'\u001b[39m\u001b[39moutput_filename_base\u001b[39m\u001b[39m'\u001b[39m: temp_name,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    285\u001b[0m         \u001b[39m'\u001b[39m\u001b[39mtimeout\u001b[39m\u001b[39m'\u001b[39m: timeout,\n\u001b[0;32m    286\u001b[0m     }\n\u001b[1;32m--> 288\u001b[0m     run_tesseract(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[0;32m    289\u001b[0m     filename \u001b[39m=\u001b[39m \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m{\u001b[39;00mkwargs[\u001b[39m'\u001b[39m\u001b[39moutput_filename_base\u001b[39m\u001b[39m'\u001b[39m]\u001b[39m}\u001b[39;00m\u001b[39m{\u001b[39;00mextsep\u001b[39m}\u001b[39;00m\u001b[39m{\u001b[39;00mextension\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    290\u001b[0m     \u001b[39mwith\u001b[39;00m \u001b[39mopen\u001b[39m(filename, \u001b[39m'\u001b[39m\u001b[39mrb\u001b[39m\u001b[39m'\u001b[39m) \u001b[39mas\u001b[39;00m output_file:\n",
      "File \u001b[1;32mc:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytesseract\\pytesseract.py:260\u001b[0m, in \u001b[0;36mrun_tesseract\u001b[1;34m(input_filename, output_filename_base, extension, lang, config, nice, timeout)\u001b[0m\n\u001b[0;32m    258\u001b[0m         \u001b[39mraise\u001b[39;00m\n\u001b[0;32m    259\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m--> 260\u001b[0m         \u001b[39mraise\u001b[39;00m TesseractNotFoundError()\n\u001b[0;32m    262\u001b[0m \u001b[39mwith\u001b[39;00m timeout_manager(proc, timeout) \u001b[39mas\u001b[39;00m error_string:\n\u001b[0;32m    263\u001b[0m     \u001b[39mif\u001b[39;00m proc\u001b[39m.\u001b[39mreturncode:\n",
      "\u001b[1;31mTesseractNotFoundError\u001b[0m: tesseract is not installed or it's not in your PATH. See README file for more information."
     ]
    }
   ],
   "source": [
    "from PIL import Image\n",
    "import pytesseract\n",
    "import os\n",
    "\n",
    "# # Specify the full path to the tesseract executable\n",
    "pytesseract.pytesseract.tesseract_cmd = r'C:\\Rijuma\\Tesseract-OCR\\tesseract.exe'\n",
    "\n",
    "# Load the image\n",
    "image_path = 'banner.jpg'  \n",
    "image = Image.open(image_path)\n",
    "\n",
    "# Extracting text from the image\n",
    "text = pytesseract.image_to_string(image)\n",
    "\n",
    "# Printing the extracted text\n",
    "print(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C90A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/cd8c090ae18fd96ea88cb9d43c778ac5.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/cd8c090ae18fd96ea88cb9d43c778ac5.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E823D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E81B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E85AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D157D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D16250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ce4b53e9ca61446123be4a4a91b966ae.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ce4b53e9ca61446123be4a4a91b966ae.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D14390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D15B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/91439bd75886de94e60d6ed7c84ccfdc.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/91439bd75886de94e60d6ed7c84ccfdc.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E84D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/4d27a167dced3f72fb470235cc676c18.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/4d27a167dced3f72fb470235cc676c18.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E88690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/0f8563469c2421d9b1c8427574a762a0.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/0f8563469c2421d9b1c8427574a762a0.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E89D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Text match flags have been added and saved to output_text_flags.csv\n"
     ]
    }
   ],
   "source": [
    "from PIL import Image\n",
    "import pytesseract\n",
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "# Specify the full path to the tesseract executable\n",
    "pytesseract.pytesseract.tesseract_cmd = r'C:\\Rijuma\\Tesseract-OCR\\tesseract.exe'\n",
    "\n",
    "# Load the image\n",
    "reference_image_path = 'banner.jpg'  # Replace with the path to your image\n",
    "reference_image = Image.open(reference_image_path)\n",
    "\n",
    "# Extract text from the image\n",
    "reference_text = pytesseract.image_to_string(reference_image)\n",
    "\n",
    "# Read the CSV file with image URLs using pandas\n",
    "csv_file_path = r'C:\\Users\\Rijuma Chitrakar\\Desktop\\project\\image.csv'\n",
    "df = pd.read_csv(csv_file_path)\n",
    "\n",
    "# Adding a new column 'Text Match Flag' to the DataFrame\n",
    "df['Text Match Flag'] = 0  # Initialize with 0\n",
    "\n",
    "for index, row in df.iterrows():\n",
    "    image_url = row['url_main_image']\n",
    "    \n",
    "    try:\n",
    "        response = requests.get(image_url, stream=True)\n",
    "        response.raise_for_status()\n",
    "        \n",
    "        # Read the image using PIL\n",
    "        img = Image.open(response.raw)\n",
    "        \n",
    "        # Extract text from the current image\n",
    "        image_text = pytesseract.image_to_string(img)\n",
    "        \n",
    "        # Compare the extracted text with the reference text\n",
    "        if reference_text in image_text:\n",
    "            df.at[index, 'Text Match Flag'] = 1\n",
    "        \n",
    "        response.close()\n",
    "    except requests.RequestException as e:\n",
    "        print(f\"Error fetching image from URL {image_url}: {e}\")\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred for URL {image_url}: {e}\")\n",
    "\n",
    "# Save the updated DataFrame to a new CSV file\n",
    "output_csv_file_path = r'C:\\Users\\Rijuma Chitrakar\\Desktop\\project\\output_text_flags.csv'\n",
    "df.to_csv(output_csv_file_path, index=False)\n",
    "\n",
    "print(\"Text match flags have been added and saved to output_text_flags.csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching image from URL https://static-01.daraz.com.np/p/ad0b87ce4ef3353ec258fdfec8426b45.png: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4AE90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B49950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B344D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2a3dcd682cffc6263bf179e0fde370d2.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2a3dcd682cffc6263bf179e0fde370d2.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE1AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE38D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE05D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE16D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE3610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE3610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/aa1affa9f9ff397dfbe4af917a76c1da.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/aa1affa9f9ff397dfbe4af917a76c1da.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE0710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2d6dab311768e6553b92b300b1938636.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2d6dab311768e6553b92b300b1938636.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE3850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e44b09734415472af286dd8787f59b29.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e44b09734415472af286dd8787f59b29.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE1DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE07D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE2D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE2A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE2110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE2390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE2AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE38D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4497c6b301161340898057edb81982cf.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4497c6b301161340898057edb81982cf.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE1A50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE01D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/88cb5f46a3a2f85b6909910dd9305881.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/88cb5f46a3a2f85b6909910dd9305881.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE16D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE17D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/431c98584708fe9e3a77eaa6de21bfc2.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/431c98584708fe9e3a77eaa6de21bfc2.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE1950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/8623137cf40b0e9f460814432cb61f38.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/8623137cf40b0e9f460814432cb61f38.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE0A50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/51b0b60e7254d628ccea38f69bc4a5fd.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/51b0b60e7254d628ccea38f69bc4a5fd.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABE0C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBEBD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/efaeda2171574c12c13627f55fa02afd.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/efaeda2171574c12c13627f55fa02afd.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2a3dcd682cffc6263bf179e0fde370d2.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2a3dcd682cffc6263bf179e0fde370d2.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBD050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/65611acda72b770a0135127fa6da015e.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/65611acda72b770a0135127fa6da015e.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B31D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBFB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBEA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFB10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B31D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa5157f14e6a569151cb524830a2be3a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa5157f14e6a569151cb524830a2be3a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBEA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/589bc3178e02d98bdf423c45d209988f.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/589bc3178e02d98bdf423c45d209988f.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736AAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBE4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBD050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBF710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/f1d08ee32239bba80d879a517cbbefbd.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/f1d08ee32239bba80d879a517cbbefbd.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBE290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/5a8fbfc1f195251b3a855788be145055.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/5a8fbfc1f195251b3a855788be145055.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B41110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B27C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4d17273bd301c17fe51ccb67adc68c09.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4d17273bd301c17fe51ccb67adc68c09.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBD0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736AAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBEA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B49D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBE2D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0A8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa5157f14e6a569151cb524830a2be3a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa5157f14e6a569151cb524830a2be3a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C923D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/f1d08ee32239bba80d879a517cbbefbd.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/f1d08ee32239bba80d879a517cbbefbd.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4B850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fcd05a561e6eed956a18739e47110484.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fcd05a561e6eed956a18739e47110484.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFA10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d591d02ea6b903de77d8398185083e94.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d591d02ea6b903de77d8398185083e94.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBE4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/b9fdfd3818b58e413d52a36c8270f274.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/b9fdfd3818b58e413d52a36c8270f274.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B253D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/f70c56ee27ae2648fa73f6aa437e987c.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/f70c56ee27ae2648fa73f6aa437e987c.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4B4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/feb6167e2892982439d210f1c0ea67c7.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/feb6167e2892982439d210f1c0ea67c7.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4B850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDD690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A2D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A2D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/8a64b56bf86ebcb7a13857391c6f885f.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/8a64b56bf86ebcb7a13857391c6f885f.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFBD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B492D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2a3dcd682cffc6263bf179e0fde370d2.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2a3dcd682cffc6263bf179e0fde370d2.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0A8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A2D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B49050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ae0f5c8947d1f38542e5059d05b32c17.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ae0f5c8947d1f38542e5059d05b32c17.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDF692FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/0303b8f3adb79610e63cb523a304eec6.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/0303b8f3adb79610e63cb523a304eec6.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B320D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDF910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/28f9ed53242dcb124988f8b1783bbf00.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/28f9ed53242dcb124988f8b1783bbf00.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906F0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/934ac2ef978037955281fcbfa17403dc.png: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/934ac2ef978037955281fcbfa17403dc.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B49A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a2f2334b552893449da0a0fc27c7de4e.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a2f2334b552893449da0a0fc27c7de4e.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDD690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/8947d4ae0da6f9dc11a5a47fa1dbd853.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/8947d4ae0da6f9dc11a5a47fa1dbd853.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906F0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFB10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9CFF9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D47A50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B48350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D47390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d591d02ea6b903de77d8398185083e94.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d591d02ea6b903de77d8398185083e94.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907F950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFA10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B30B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C7F9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2f6a1756800e6e616c56c03797f7bedf.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2f6a1756800e6e616c56c03797f7bedf.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B49810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFB10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/15f8f2def7e8e772ecdc7d75e2ba2afc.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/15f8f2def7e8e772ecdc7d75e2ba2afc.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B35FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/6eb849fb496f9d954f4fa85da5c4ce3d.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/6eb849fb496f9d954f4fa85da5c4ce3d.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFB90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736AAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4bc867583def8ac4b556b6a6d5cde215.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4bc867583def8ac4b556b6a6d5cde215.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9EDFB90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDFC1A050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/b205e5e47414572cdf9b70f94f967d60.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/b205e5e47414572cdf9b70f94f967d60.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0A890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa5157f14e6a569151cb524830a2be3a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa5157f14e6a569151cb524830a2be3a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906FB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDF692390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4bc867583def8ac4b556b6a6d5cde215.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4bc867583def8ac4b556b6a6d5cde215.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B4A9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDF692390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ebcfd52fe247e38f802614d4c32981c6.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ebcfd52fe247e38f802614d4c32981c6.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4d27a167dced3f72fb470235cc676c18.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4d27a167dced3f72fb470235cc676c18.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B30B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/57afd8c4f2727abd3fe28d38ca23e0c4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/57afd8c4f2727abd3fe28d38ca23e0c4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E090D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33F50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2a3dcd682cffc6263bf179e0fde370d2.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2a3dcd682cffc6263bf179e0fde370d2.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAADCB10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906FB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAADFC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAADFC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4bc867583def8ac4b556b6a6d5cde215.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4bc867583def8ac4b556b6a6d5cde215.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0B650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33F50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDF692390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906FA10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/63c4059a8190d0c0363556e556921f4f.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/63c4059a8190d0c0363556e556921f4f.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B34610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B30D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907F950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a0cd06782c2547ce05c2896610191f1a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a0cd06782c2547ce05c2896610191f1a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/f1d08ee32239bba80d879a517cbbefbd.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/f1d08ee32239bba80d879a517cbbefbd.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907A1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAB4ECD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d57bcdb15d10086bf0bf7c01ef7875d1.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d57bcdb15d10086bf0bf7c01ef7875d1.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/0f2e3ff6445f21326a00d617b472112b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/0f2e3ff6445f21326a00d617b472112b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDFC1B7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B43950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906FA10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2a3dcd682cffc6263bf179e0fde370d2.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2a3dcd682cffc6263bf179e0fde370d2.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B353D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/582a870f91ff6170307902994b3f587d.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/582a870f91ff6170307902994b3f587d.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B30DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF90BB990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B27C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a48ce5ac6d39df26ceccb2ad6d8505be.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906FA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B35510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906F290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a2f2334b552893449da0a0fc27c7de4e.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a2f2334b552893449da0a0fc27c7de4e.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D16B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C85410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736AAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2ec775d3867803536ec38d115bcb26d1.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2ec775d3867803536ec38d115bcb26d1.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDF692FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C85650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/95a09059bca5d792d51a3c8c8285b2a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/95a09059bca5d792d51a3c8c8285b2a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/2920a5ade2728f5fec2981d83cf1b9f6.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/2920a5ade2728f5fec2981d83cf1b9f6.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B253D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D32490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e059484d7e2c220c9a18230c024337e9.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e059484d7e2c220c9a18230c024337e9.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E27190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C92990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907A650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/a2f2334b552893449da0a0fc27c7de4e.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/a2f2334b552893449da0a0fc27c7de4e.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C92990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAADC510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa5157f14e6a569151cb524830a2be3a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa5157f14e6a569151cb524830a2be3a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D47090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736AAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/692abccaa44c1a69f47d353bd75a5330.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/692abccaa44c1a69f47d353bd75a5330.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D32490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/92901f4179246f92864f18668aabd988.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/92901f4179246f92864f18668aabd988.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907FAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D47F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/1901c2fad6c580a1f82354ee9ba8d38b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/1901c2fad6c580a1f82354ee9ba8d38b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D32410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/06d5e76317e13768e6d195530673f29a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/06d5e76317e13768e6d195530673f29a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907FAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907A510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B32B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAB4ECD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906F290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/8947d4ae0da6f9dc11a5a47fa1dbd853.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/8947d4ae0da6f9dc11a5a47fa1dbd853.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B31C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907FAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E27190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9097850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D32410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/585fda13e9df942a35a63541d2337f48.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/585fda13e9df942a35a63541d2337f48.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D16AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/498ebbfabf8d17b3e24f0f155e95157b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/498ebbfabf8d17b3e24f0f155e95157b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAADC510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0A8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B31C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B35590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0A610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/10e7ba63d7085a39e06e2ae87f0ba099.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/10e7ba63d7085a39e06e2ae87f0ba099.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907B710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/91439bd75886de94e60d6ed7c84ccfdc.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/91439bd75886de94e60d6ed7c84ccfdc.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9C85650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ffbfa85a5fb1e48085c992b040d47613.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ffbfa85a5fb1e48085c992b040d47613.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B43950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/07f721e90c159b85576bf188ac99d444.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/07f721e90c159b85576bf188ac99d444.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0A610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa5157f14e6a569151cb524830a2be3a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa5157f14e6a569151cb524830a2be3a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E82D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ae0f5c8947d1f38542e5059d05b32c17.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ae0f5c8947d1f38542e5059d05b32c17.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E87290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live-21.slatic.net/kf/S11c7d529656241f7b994f9e9c1774960R.jpg: HTTPSConnectionPool(host='np-live-21.slatic.net', port=443): Max retries exceeded with url: /kf/S11c7d529656241f7b994f9e9c1774960R.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907A6D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E82D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906FB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/df57a79f5c1a59b33d978ac1c19e8bb8.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/df57a79f5c1a59b33d978ac1c19e8bb8.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B253D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9097990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAADFC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B35210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/589bc3178e02d98bdf423c45d209988f.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/589bc3178e02d98bdf423c45d209988f.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B25190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live-21.slatic.net/kf/Sc4be5782d1f64e08b8e07a46426a1e95V.jpg: HTTPSConnectionPool(host='np-live-21.slatic.net', port=443): Max retries exceeded with url: /kf/Sc4be5782d1f64e08b8e07a46426a1e95V.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9CFF9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF90B6A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/5e565ce9c63c5a21a6021a3135d31f41.png: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/5e565ce9c63c5a21a6021a3135d31f41.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4c8c6c7bb85b045f9f0fc66d9c8584eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4c8c6c7bb85b045f9f0fc66d9c8584eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFA4B2C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736AA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/59525e0118befb39e7a5459d91a31ded.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/59525e0118befb39e7a5459d91a31ded.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907A710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d93174073f7ff0633fd273a32a440983.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d93174073f7ff0633fd273a32a440983.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906F7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fa5157f14e6a569151cb524830a2be3a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fa5157f14e6a569151cb524830a2be3a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906F7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907B0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF906F7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4d27a167dced3f72fb470235cc676c18.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4d27a167dced3f72fb470235cc676c18.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B42510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907F950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6e482c82dd925cebbdec7a3b0b55a09.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6e482c82dd925cebbdec7a3b0b55a09.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAADC510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ebcfd52fe247e38f802614d4c32981c6.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ebcfd52fe247e38f802614d4c32981c6.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B34610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/0b65b2cac6901277083417288125bb4a.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/0b65b2cac6901277083417288125bb4a.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B425D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D16B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/eb2abb62d0093bf97c22c49714a3d84e.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/eb2abb62d0093bf97c22c49714a3d84e.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDFC1A610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/4d27a167dced3f72fb470235cc676c18.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/4d27a167dced3f72fb470235cc676c18.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFA4B2C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/8947d4ae0da6f9dc11a5a47fa1dbd853.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/8947d4ae0da6f9dc11a5a47fa1dbd853.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E82D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ffa6b219f536fe76d55adfdc28c1d667.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ffa6b219f536fe76d55adfdc28c1d667.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFA4B2C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e6633271fe957e7fbfd82d362fe4b883.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e6633271fe957e7fbfd82d362fe4b883.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF90B76D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d591d02ea6b903de77d8398185083e94.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d591d02ea6b903de77d8398185083e94.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDFC1A610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/e43a0c206458eb2f3dbc5421cf509dd8.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/e43a0c206458eb2f3dbc5421cf509dd8.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E27F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D47A50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9E0BBD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF907FBD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/9c65b81920c4b5e7bdd50488dbc7f9f9.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/9c65b81920c4b5e7bdd50488dbc7f9f9.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAB4F350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEDFC1A450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/d4fea42bb8a119c3298cebd1f7f5bc10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B33ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/ffb93bee99b7d5133d91c2be9d3188c7.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/ffb93bee99b7d5133d91c2be9d3188c7.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF9D16AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/cfb1226ea0f8f403c170b2df92663f41.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/cfb1226ea0f8f403c170b2df92663f41.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736A250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/fc3a12b4d4f1e296e868ef6feee0f8dc.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/fc3a12b4d4f1e296e868ef6feee0f8dc.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/679bf35ca2108d3a7fe11b25b45041ed.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/679bf35ca2108d3a7fe11b25b45041ed.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF736AAD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEF8B40BD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://static-01.daraz.com.np/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='static-01.daraz.com.np', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFABBFE10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAC82010>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE800088D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8002A8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80028B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8003AD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8001CF50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8008B5D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80089D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8008B990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80099110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80099650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Text match flags have been added and saved to output_text_flags.csv\n"
     ]
    }
   ],
   "source": [
    "from PIL import Image\n",
    "import pytesseract\n",
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "# Specify the full path to the tesseract executable\n",
    "pytesseract.pytesseract.tesseract_cmd = r'C:\\Rijuma\\Tesseract-OCR\\tesseract.exe'\n",
    "\n",
    "# Load the reference banner image\n",
    "reference_image_path = 'banner.jpg' \n",
    "reference_image = Image.open(reference_image_path)\n",
    "\n",
    "# Extract text from the reference banner image\n",
    "reference_text = pytesseract.image_to_string(reference_image)\n",
    "\n",
    "# Read the CSV file with image URLs using pandas\n",
    "df = pd.read_csv('image2.csv')\n",
    "\n",
    "# Create a new column 'Text Match Flag' to the DataFrame\n",
    "df['Text Match Flag'] = 0  # Initialize with 0\n",
    "\n",
    "# Iterate through each row in the DataFrame\n",
    "for index, row in df.iterrows():\n",
    "    image_url = row['url_main_image']\n",
    "    \n",
    "    try:\n",
    "        response = requests.get(image_url, stream=True)\n",
    "        response.raise_for_status()\n",
    "        \n",
    "        # Read the image using PIL\n",
    "        img = Image.open(response.raw)\n",
    "        \n",
    "        # Extract text from the current image\n",
    "        image_text = pytesseract.image_to_string(img)\n",
    "        \n",
    "        # Compare the extracted text with the reference text\n",
    "        if reference_text in image_text:\n",
    "            df.at[index, 'Text Match Flag'] = 1\n",
    "        \n",
    "        response.close()\n",
    "    except requests.RequestException as e:\n",
    "        print(f\"Error fetching image from URL {image_url}: {e}\")\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred for URL {image_url}: {e}\")\n",
    "\n",
    "# Save the updated DataFrame to a new CSV file\n",
    "output_csv_file_path = r'C:\\Users\\Rijuma Chitrakar\\Desktop\\project\\outputs.csv'\n",
    "df.to_csv(output_csv_file_path, index=False)\n",
    "\n",
    "print(\"Text match flags have been added and saved to output_text_flags.csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching image from URL https://np-live.slatic.net/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80F13350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE802AC710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80281A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8064EC90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8064C8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE806302D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80681450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8067E150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80712790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80682410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8071C8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80681850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80707010>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80682550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE807E2150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE807E13D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80772CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Non-matching data has been saved to C:\\Users\\Rijuma Chitrakar\\Desktop\\project\\non_matching_data.csv\n"
     ]
    }
   ],
   "source": [
    "#extraxting product id and name\n",
    "\n",
    "from PIL import Image\n",
    "import pytesseract\n",
    "import requests\n",
    "import pandas as pd\n",
    "from fuzzywuzzy import fuzz\n",
    "from concurrent.futures import ThreadPoolExecutor\n",
    "\n",
    "# Specify the full path to the tesseract executable\n",
    "pytesseract.pytesseract.tesseract_cmd = r'C:\\Rijuma\\Tesseract-OCR\\tesseract.exe'\n",
    "\n",
    "# Load the reference banner image\n",
    "reference_image_path = 'banner.jpg'  # Replace with the path to your image\n",
    "reference_image = Image.open(reference_image_path)\n",
    "\n",
    "# Extract text from the reference banner image\n",
    "reference_text = pytesseract.image_to_string(reference_image)\n",
    "\n",
    "# Read the CSV file with image URLs using pandas\n",
    "csv_file_path = r'C:\\Users\\Rijuma Chitrakar\\Desktop\\project\\image2.csv'\n",
    "df = pd.read_csv(csv_file_path)\n",
    "\n",
    "# Set a similarity threshold to determine if it's a match\n",
    "similarity_threshold = 80\n",
    "\n",
    "# Function to process a single row and return the product info if it does not match\n",
    "def process_row(row):\n",
    "    image_url = row.url_main_image\n",
    "    \n",
    "    try:\n",
    "        response = requests.get(image_url, stream=True)\n",
    "        response.raise_for_status()\n",
    "        \n",
    "        # Read the image using PIL\n",
    "        img = Image.open(response.raw)\n",
    "        \n",
    "        # Extract text from the current image\n",
    "        image_text = pytesseract.image_to_string(img)\n",
    "        \n",
    "        # Calculate text similarity using fuzz.ratio()\n",
    "        similarity_score = fuzz.ratio(reference_text.lower(), image_text.lower())\n",
    "        \n",
    "        # Compare the similarity score with the threshold\n",
    "        if similarity_score < similarity_threshold:\n",
    "            return {\n",
    "                'product_id': row.product_id,\n",
    "                'product_name': row.product_name\n",
    "            }\n",
    "        \n",
    "        response.close()\n",
    "    except requests.RequestException as e:\n",
    "        print(f\"Error fetching image from URL {image_url}: {e}\")\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred for URL {image_url}: {e}\")\n",
    "    \n",
    "    return None\n",
    "\n",
    "# Process rows concurrently using ThreadPoolExecutor\n",
    "non_matching_data = []\n",
    "with ThreadPoolExecutor(max_workers=8) as executor:\n",
    "    results = executor.map(process_row, df.itertuples(index=False))\n",
    "    for data in results:\n",
    "        if data:\n",
    "            non_matching_data.append(data)\n",
    "\n",
    "# Create a DataFrame for the non-matching data\n",
    "output_df = pd.DataFrame(non_matching_data)\n",
    "\n",
    "# Save the non-matching data to a CSV file\n",
    "output_csv_file_path = r'C:\\Users\\Rijuma Chitrakar\\Desktop\\project\\non_matching_data.csv'\n",
    "output_df.to_csv(output_csv_file_path, index=False)\n",
    "\n",
    "print(f\"Non-matching data has been saved to {output_csv_file_path}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching image from URL https://np-live.slatic.net/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE81256850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/fa7dd5dc29a67e33bc3242b1a715da12.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/fa7dd5dc29a67e33bc3242b1a715da12.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8126E110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE81214610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8047C890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8047CD10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE8047E590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80449490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80451150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/ff79d3a7ab82ae454f9335fa59060a53.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/ff79d3a7ab82ae454f9335fa59060a53.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80407D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80406F50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/166606f268db2b0b122e697377e6a8a4.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/166606f268db2b0b122e697377e6a8a4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE803FBC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFAB3F010>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80EF49D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80EF6F50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/177985bab385a6eb431873b275d7d6eb.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/177985bab385a6eb431873b275d7d6eb.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80EF5750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80EF4750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error fetching image from URL https://np-live.slatic.net/p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg: HTTPSConnectionPool(host='np-live.slatic.net', port=443): Max retries exceeded with url: /p/35c4ba5756c0eb0ecedf1afda5d91c0b.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE80ECDE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Text match flags have been added and saved to outputs.csv\n"
     ]
    }
   ],
   "source": [
    "#accurate test\n",
    "from PIL import Image\n",
    "import pytesseract\n",
    "import requests\n",
    "import pandas as pd\n",
    "from fuzzywuzzy import fuzz\n",
    "\n",
    "# Specify the full path to the tesseract executable\n",
    "pytesseract.pytesseract.tesseract_cmd = r'C:\\Rijuma\\Tesseract-OCR\\tesseract.exe'\n",
    "\n",
    "# Load the reference banner image\n",
    "reference_image_path = 'banner.jpg'\n",
    "reference_image = Image.open(reference_image_path)\n",
    "\n",
    "# Extract text from the reference banner image\n",
    "reference_text = pytesseract.image_to_string(reference_image)\n",
    "\n",
    "# Read the CSV file with image URLs using pandas\n",
    "df = pd.read_csv('image2.csv')\n",
    "\n",
    "# Create a new column 'Text Match Flag' to the DataFrame\n",
    "df['Text Match Flag'] = 0  # Initialize with 0\n",
    "\n",
    "# Set a similarity threshold for fuzzy matching\n",
    "similarity_threshold = 80\n",
    "\n",
    "# Iterate through each row in the DataFrame\n",
    "for index, row in df.iterrows():\n",
    "    image_url = row['url_main_image']\n",
    "    \n",
    "    try:\n",
    "        response = requests.get(image_url, stream=True)\n",
    "        response.raise_for_status()\n",
    "        \n",
    "        # Read the image using PIL\n",
    "        img = Image.open(response.raw)\n",
    "        \n",
    "        # Extract text from the current image\n",
    "        image_text = pytesseract.image_to_string(img)\n",
    "        \n",
    "        # Calculate text similarity using fuzz.ratio()\n",
    "        similarity_score = fuzz.ratio(reference_text.lower(), image_text.lower())\n",
    "        \n",
    "        # Compare the similarity score with the threshold\n",
    "        if similarity_score >= similarity_threshold:\n",
    "            df.at[index, 'Text Match Flag'] = 1\n",
    "        \n",
    "        response.close()\n",
    "    except requests.RequestException as e:\n",
    "        print(f\"Error fetching image from URL {image_url}: {e}\")\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred for URL {image_url}: {e}\")\n",
    "\n",
    "# Save the updated DataFrame to a new CSV file\n",
    "output_csv_file_path = r'C:\\Users\\Rijuma Chitrakar\\Desktop\\project\\outputs.csv'\n",
    "df.to_csv(output_csv_file_path, index=False)\n",
    "\n",
    "print(\"Text match flags have been added and saved to outputs.csv\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
